name: peminjam_perpustakaan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.0.3
  get: 4.6.6
  intl: 0.19.0
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.0.0
  lottie: ^2.7.0
  hexcolor: ^3.0.1
  google_fonts: 6.1.0
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/logo/
  - assets/cover/
  - assets/lottie/
  - assets/lottie/welcome.json

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo1_perpnn.png
  android: true
  ios: true
  web: true